### ISSUE TITLE
Ability to ignore specific code similar to `@ts-ignore`

### ISSUE THREAD

**Issue by KamilDev** [micromark/micromark-extension-mdx-expression#10]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=issues) and [discussions](https://github.com/orgs/micromark/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

When using a templating language inside MDX, you will get the following error:
```liquid
{% include "api-docs-table.liquid", apiDoc: "apiDocs.converter" %}
```

> Could not parse expression with acornMDX ([micromark-extension-mdx-expression:acorn](https://github.com/micromark/micromark-extension-mdx-expression/tree/main/packages/micromark-extension-mdx-expression#could-not-parse-expression-with-acorn))

### Current solutions

I have not found any current way to ignore the error.

### Proposed solutions

It would be great to be able to ignore expected errors, for example similar to `@ts-ignore`:
```mdx
{ /* @mdx-ignore */ }
{% include "api-docs-table.liquid", apiDoc: "apiDocs.converter" %}
```

**Comment by remcohaszing** [comment]
Related:

- https://github.com/orgs/micromark/discussions/188
- https://github.com/mdx-js/mdx-analyzer/issues/267
- https://github.com/micromark/micromark-extension-mdx-jsx/issues/10

**Comment by ChristianMurphy** [comment]
Welcome @KamilDev! 👋 
Thanks for sharing your idea.

Remark/MDX has a way to support syntax extensions, including the one you describe, see https://github.com/micromark/micromark?tab=readme-ov-file#extending-markdown and https://github.com/micromark/micromark?tab=readme-ov-file#creating-a-micromark-extension (define what valid syntax is)

And has a way to disable lint rules https://github.com/remarkjs/remark-lint/tree/main?tab=readme-ov-file#ignore-warnings (check control flow and styling of valid syntax)

What you want is a loose mode (with a flag) for MDX, which fundamentally conflicts with the language goal.
MDX is Markdown + JSX, JSX is is JS + XML.
Neither JavaScript nor XML allow invalid syntax to exist within a document.

If you need a more forgiving parser.
Use markdown, there is no such thing as an invalid document in plain markdown.

There will not be a loose mode in core MDX.

---

To address your need which is implied through this.
You want to be able to import external documents.
MDX supports this, it is one of the core language features, imports https://mdxjs.com/docs/what-is-mdx/#esm
This means you can import and embed MDX document inside of others.

Additionally, when paired with a build tool/bundler it can import any file/document type that the build tool supports.
For example an external handlebars template https://github.com/mixmaxhq/rollup-plugin-handlebars-plus

If you want to use MDX, use it, don't make up another language.
