### ISSUE TITLE
`options.acornOptions.onComment` is overridden internally, which makes `comments` unavailable from outside

### ISSUE THREAD

**Issue by JounQin** [micromark/micromark-extension-mdx-expression#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-util-events-to-acorn

### Link to runnable example

https://github.com/micromark/micromark-extension-mdx-expression/blob/main/packages/micromark-util-events-to-acorn/dev/index.js#L44

### Steps to reproduce

No need

### Expected behavior

Reuse `options.acornOptions.onComment` if provided

### Actual behavior

`options.acornOptions.onComment` is overridden

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

**Comment by JounQin** [comment]
Proposal:

```js
/** @type {AcornOptions} */
const acornOptions = options.acornOptions || {};
const onComment = acornOptions.onComment;

/** @type {Array.<Comment>} */
const comments = Array.isArray(onComment) ? onComment : [];

const acornConfig = Object.assign({}, options.acornOptions, {
  onComment:
    typeof onComment === "function"
      ? /**
         *
         * @param {boolean} isBlock
         * @param {string} text
         * @param {number} start
         * @param {number} end
         * @param {Position} [startLoc]
         * @param {Position} [endLoc]
         */
        function (isBlock, text, start, end, startLoc, endLoc) {
          const comment = {
            type: isBlock ? "Block" : "Line",
            value: text,
            start: start,
            end: end,
          };
          if (acornOptions.locations) {
            comment.loc = new options.acorn.SourceLocation(
              this,
              startLoc,
              endLoc
            );
          }
          if (acornOptions.ranges) {
            comment.range = [start, end];
          }
          comments.push(comment);
          onComment.call(this, isBlock, text, start, end, startLoc, endLoc);
        }
      : comments,
  preserveParens: true,
});
```

**Comment by JounQin** [comment]
I found function type of `acornOptions .onComment` should not be used because the loc is wrong by default.

**Comment by wooorm** [comment]
Sorry I commented on the PR, can we discuss there?
