### ISSUE TITLE
`prefix/suffix` should not be passed to `onToken`

### ISSUE THREAD

**Issue by JounQin** [micromark/micromark-extension-mdx-expression#6]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-extension-mdx-expression

### Link to runnable example

https://github.com/mdx-js/eslint-mdx/pull/394#discussion_r872988645

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by wooorm** [comment]
Thanks for raising!
