### ISSUE TITLE
Get error "'estree-util-visit/index' has no exported member 'Node'."

### ISSUE THREAD

**Issue by rognierbenoit** [micromark/micromark-extension-mdx-expression#8]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.2.0

### Steps to reproduce

A typescript project using the lib

### Expected behavior

Should compile.

### Actual behavior

```
Namespace '".../node_modules/estree-util-visit/index"' has no exported member 'Node'.

23 export type EstreeNode = import('estree-util-visit').Node
                                                        ~~~~
```

estree-util-visit has no exported 'Node' type.

The solution is to comment the line out ?

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
> The solution is to comment the line out ?

No, that is not a solution. Why would you use TypeScript but not want types? That doesn’t make sense.

The solution is either:
- to import `Node` from the correct place here
- for you to set `"skipLibCheck": true,` in your TS config file

**Comment by remcohaszing** [comment]
That’s what they’re reporting. `micromark-extension-mdx-expression` imports `Node` from the wrong place. This is fixed in https://github.com/micromark/micromark-extension-mdx-expression/commit/350fe0bf8d0fae9cf1d619585af87905b692aa5d#diff-862b7cc1d1766f73cb7e1e22ecf87e00ec4a42a5118941f5fd4039844f6abaa0, but it hasn’t been released yet.

**Comment by wooorm** [comment]
Thanks for the report! released a fix: https://github.com/micromark/micromark-extension-mdx-expression/releases
